name: protein_eng
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - amqp=5.2.0=pyhd8ed1ab_2
  - anyio=4.10.0=pyhe01879c_0
  - appdirs=1.4.4=pyhd8ed1ab_1
  - appnope=0.1.4=pyhd8ed1ab_1
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py39he7485ab_0
  - arrow=1.3.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.3.0=pyh71513ae_0
  - babel=2.17.0=pyhd8ed1ab_0
  - bcrypt=4.3.0=py39h51e8d5a_1
  - beautifulsoup4=4.13.4=pyha770c72_0
  - billiard=3.6.4.0=py39h02fc5c5_3
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - brotli=1.2.0=h7d5ae5b_1
  - brotli-bin=1.2.0=hc919400_1
  - brotli-python=1.0.9=py39h23fbdae_8
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - celery=5.2.7=pyhd8ed1ab_0
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py39h7f933ea_0
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - click-didyoumean=0.3.1=pyhd8ed1ab_1
  - click-plugins=1.1.1.2=pyhd8ed1ab_0
  - click-repl=0.3.0=pyhd8ed1ab_0
  - comm=0.2.3=pyhe01879c_0
  - commonmark=0.9.1=py_0
  - contourpy=1.3.0=py39h85b62ae_2
  - cryptography=45.0.6=py39hda141db_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - dataclasses=0.8=pyhc8e2a94_3
  - debugpy=1.8.16=py39hd866990_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - docker-py=7.1.0=pyhd8ed1ab_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - flask=2.2.5=pyhd8ed1ab_0
  - flask-cors=6.0.1=pyhe01879c_0
  - fonttools=4.59.1=py39hb270ea8_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.14.1=hce30654_0
  - future=1.0.0=pyhd8ed1ab_2
  - gmp=6.3.0=h7bae524_2
  - gunicorn=23.0.0=py39h2804cbe_1
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.2.0=pyhd8ed1ab_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.2=h38cb7af_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - invoke=2.2.0=pyhd8ed1ab_1
  - ipykernel=6.30.1=pyh92f572d_0
  - ipython=8.18.1=pyh707e725_3
  - ipywidgets=8.1.7=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - itsdangerous=2.2.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py39h2804cbe_1
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.4.1=pyh29332c3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter=1.1.1=pyhd8ed1ab_1
  - jupyter-lsp=2.2.6=pyhe01879c_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_console=6.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.16.0=pyhe01879c_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.6=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - jupyterlab_widgets=3.0.15=pyhd8ed1ab_0
  - kiwisolver=1.4.7=py39h157d57c_0
  - kombu=5.3.3=py39h2804cbe_0
  - krb5=1.21.3=h237132a_0
  - lark=1.2.2=pyhd8ed1ab_1
  - lcms2=2.18=hdfa7624_0
  - lerc=4.0.0=hd64df32_1
  - libblas=3.11.0=5_h51639a9_openblas
  - libbrotlicommon=1.2.0=hc919400_1
  - libbrotlidec=1.2.0=hc919400_1
  - libbrotlienc=1.2.0=hc919400_1
  - libcblas=3.11.0=5_hb0561ab_openblas
  - libcxx=21.1.8=h55c6f16_2
  - libdeflate=1.25=hc11a715_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libexpat=2.7.3=haf25636_0
  - libffi=3.5.2=hcf2aa1b_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgcc=15.2.0=hcbb3090_17
  - libgfortran=15.2.0=h07b0088_17
  - libgfortran5=15.2.0=hdae7583_17
  - libjpeg-turbo=3.1.2=hc919400_0
  - liblapack=3.11.0=5_hd9741b5_openblas
  - liblzma=5.8.2=h8088a28_0
  - libopenblas=0.3.30=openmp_ha158390_4
  - libpng=1.6.54=h132b30e_0
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.51.2=h1ae2325_0
  - libtiff=4.7.1=h4030677_1
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.8=h4a912ad_0
  - markupsafe=3.0.2=py39hefdd603_1
  - matplotlib=3.9.4=py39hdf13c20_0
  - matplotlib-base=3.9.4=py39h7251d6c_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mistune=3.1.3=pyh29332c3_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - nbclient=0.10.4=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - notebook=7.4.5=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - openjpeg=2.5.4=hbfb3c88_0
  - openssl=3.6.1=hd24854e_1
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=26.0=pyhcf101f3_0
  - pandas=2.3.1=py39h6aaa60c_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - paramiko=4.0.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py39hfea3036_0
  - pip=25.2=pyh8b19718_0
  - platformdirs=4.3.8=pyhe01879c_0
  - prometheus_client=0.22.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - prompt_toolkit=3.0.51=hd8ed1ab_0
  - psutil=7.0.0=py39hf3bc14e_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pybiolib=1.1.862=pyhdfd78af_0
  - pycparser=2.22=pyh29332c3_1
  - pycryptodome=3.23.0=py39h979d68b_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyjwt=2.10.1=pyhd8ed1ab_0
  - pynacl=1.5.0=py39h06df861_4
  - pyobjc-core=11.0=py39hebff0d6_0
  - pyobjc-framework-cocoa=11.0=py39hebff0d6_0
  - pyparsing=3.2.3=pyhe01879c_2
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.9.23=h7139b31_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.9=8_cp39
  - pytz=2025.2=pyhd8ed1ab_0
  - pywin32-on-windows=0.1.0=pyh1179c8e_3
  - pyyaml=6.0.2=py39hefdd603_2
  - pyzmq=27.0.2=py39h6c7bd39_0
  - qhull=2020.2=h420ef59_5
  - readline=8.3=h46df422_0
  - referencing=0.36.2=pyh29332c3_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rich=12.6.0=pyhd8ed1ab_0
  - rpds-py=0.27.0=py39hf64921a_0
  - send2trash=1.8.3=pyh31c8845_1
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sniffio=1.3.1=pyhd8ed1ab_1
  - soupsieve=2.7=pyhd8ed1ab_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - terminado=0.18.1=pyh31c8845_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=h010d191_3
  - tomli=2.2.1=pyhe01879c_2
  - tornado=6.5.2=py39he7485ab_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - types-python-dateutil=2.9.0.20250809=pyhd8ed1ab_0
  - typing-extensions=4.14.1=h4440ef1_0
  - typing_extensions=4.14.1=pyhe01879c_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025c=hc9c84f9_1
  - unicodedata2=16.0.0=py39hf3bc14e_0
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - vine=5.1.0=pyhd8ed1ab_1
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=4.0.14=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=hc919400_1
  - xorg-libxdmcp=1.1.5=hc919400_1
  - yaml=0.2.5=h925e9cb_3
  - zeromq=4.3.5=h888dc83_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zstandard=0.23.0=py39he7485ab_3
  - zstd=1.5.7=hbf9d68e_6
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - antlr4-python3-runtime==4.9.3
      - async-timeout==5.0.1
      - biopython==1.84
      - boltz==0.4.1
      - click==8.1.7
      - dm-tree==0.1.8
      - dnachisel==3.2.16
      - docker-pycreds==0.4.0
      - docopt==0.6.2
      - einops==0.8.0
      - einx==0.3.0
      - fairscale==0.4.13
      - filelock==3.19.1
      - flametree==0.2.1
      - frozendict==2.4.7
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - hydra-core==1.3.2
      - ihm==2.9
      - lightning-utilities==0.15.2
      - mashumaro==3.14
      - modelcif==1.2
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multidict==6.7.1
      - networkx==3.2.1
      - numpy==1.26.3
      - omegaconf==2.3.0
      - prettytable==3.16.0
      - proglog==0.1.12
      - propcache==0.4.1
      - protobuf==5.29.6
      - py3dmol==2.5.4
      - pydivsufsort==0.0.20
      - pydna==5.5.3
      - pyfiglet==0.8.post1
      - python-codon-tables==0.1.18
      - pytorch-lightning==2.4.0
      - rdkit==2025.9.2
      - regex==2024.11.6
      - requests==2.32.3
      - scipy==1.13.1
      - seguid==0.2.1
      - sentry-sdk==2.52.0
      - setproctitle==1.3.7
      - smmap==5.0.2
      - sympy==1.14.0
      - torch==2.8.0
      - torchmetrics==1.8.2
      - tqdm==4.67.3
      - types-requests==2.32.4.20260107
      - wandb==0.18.7
      - yarl==1.22.0
prefix: /Users/rajkumar/miniconda3/envs/protein_eng
